USE Escola;
GO

--SELECT PARA CONSULTAS SIMPLES
SELECT * FROM Professor


-- UTILIZANDO WHERE + SELECT PARA LIMITAR OS RESULTADOS DE CONSULTAS
SELECT * FROM Professor
WHERE Nome = 'Everton';


--UTILIZANDO WHERE BETWEEN PERMITE DEFINIR UM INTERVALO DE VALORES A SER SELECIONADO
SELECT * FROM Professor
WHERE Ano_Materia == 2023 AND Ano_Materia == 2024;


--UTILIZANDO WHERE IN CRIA UMA LISTA DE DADOS QUE SERÁ RETORNADO NA CONSULTA
SELECT Nome_Aluno FROM Aluno
WHERE Nome_Aluno IN ('Beatriz', 'Olivia', 'Willian');


--UTILIZANDO WHERE NOT PARA NÃO VISUALIZAR ALGUM DADO EM UMA CONSULTA
SELECT * FROM Professor
WHERE Nome NOT IN ('Danile', 'Hugo','Adriana', 'Gabriela')


--UTILIZANDO WHERE LIKE PARA VERIFICAR SE UMA SÉRIE DE CARACTERES CORESPONDE A UM PADRÃO ESPECIFICADO
SELECT * FROM Aluno
WHERE Nome_Aluno LIKE '%é%';


-- UTILIZANDO UPDATE PARA ATUALIZAR REGISTROS
UPDATE Professor
SET Nome = 'Felipe' WHERE Nome = 'Everton'

SELECT * FROM Professor
WHERE Nome = 'Felipe'



--UTILIZANDO DELETE PARA APAGAR REGISTROS
--DELETE FROM Professor
 --WHERE Nome = 'Felipe'


